### ISSUE TITLE
loadjpeg_linux.o - No such file or directory (Building)

### ISSUE THREAD

**Issue by gbudny** [brizzly/Halloween3D#11]
Hi

I trird to build this new version on Ubuntu 20.4, and I noticed this issue:

https://gist.github.com/gbudny/c0f6ba0d3a011429a49fb5d29d77aff7

**Comment by gbudny** [comment]
I installed turbojpeg-dev and in the build file I changed loadjpeg_linux.o toloadjpeg_linux.h. This allowed me to build few more seconds to this point:

https://gist.github.com/gbudny/14a4d03522cfbc627df2bb4acdc11966

I used cmake to build it and the game runs now on Linux!

**Comment by pocak100** [comment]
Right, turbojpeg-dev is required now. After installing that, what do you get with the original build file?

**Comment by gbudny** [comment]
Well, the build script can't create the halloween file, and it would nice if this could be fixed. You can see this issue in my second gist.

When I used cmake instead the build script, and it just builds the file halloween without any issues. Later, I used it to run Halloween, and it's playable on Linux. It's so amazing what you have done with the source code.

This is an issue only with the build script that now shouldn't be used to build Halloween on Linux.

**Comment by brizzly** [comment]
You are amazing guys !
If I though about that 20 years ago when I wrote this game... :)
I will buy a PC with Linux in a couple of month.

**Comment by brizzly** [comment]
cd Halloween3D/HalloweenSrc

mkdir Build

cd Build

cmake ..

make
