### ISSUE TITLE
windows.h: No such file or directory - Ubuntu 20.4

### ISSUE THREAD

**Issue by gbudny** [brizzly/Halloween3D#2]
Hi

I try to build this game on Ubuntu 20.4, and I installed libsdl-dev because there was warning about missing: sdl-config: command not found. Later, I copied all .cpp and .h files to the directory projet_linux, and I modified  the build script to detect all .cpp files instead .c files and .h files instead .o files. 

I noticed that the warning:windows.h: No such file or directory prevents it from building on Linux. I read that I don't need it so I can remove this line, or use this code:

#ifdef __WINDOWS__ 
#include <windows.h>
#endif

https://gist.github.com/gbudny/fa125a136baba88bc9ba4f5616247e41

https://stackoverflow.com/questions/35665881/error-when-compiling-on-g/35665941#35665941

What's a better solution in this case?

**Comment by brizzly** [comment]
Hello!
In this file : https://github.com/brizzly/Halloween3D/blob/master/HalloweenSrc/alloween.h
Please comment H_WINDOWS and uncomment H_WINDOWS

//#define H_MAC
//#define H_LINUX
#define H_WINDOWS

**Comment by gbudny** [comment]
Hi

Thank you for the answer.

Do you think about commenting H_WINDOWS and uncommenting H_LINUX?

I hope that I did it correctly:

//#define H_MAC
#define H_LINUX
//#define H_WINDOWS

https://gist.github.com/gbudny/2a80f49edd1022d5a0650b71b1bdc125

**Comment by gbudny** [comment]
Thank you. 

This issue is solved.
