### ISSUE TITLE
Missing a body_Red.jpg file

### ISSUE THREAD

**Issue by gbudny** [brizzly/Halloween3D#20]
Hi

I found another issue with a missing texture file, but this time it exists in the test version of Halloween:

body_Red.tga
body_Red.jpg
Error in loading the image: system/textures/body_Red.jpg
Loading: system/entity/monstre.ent
body_Red.tga
body_Red.jpg
Error in loading the image: system/textures/body_Red.jpg

https://github.com/brizzly/Halloween3D_Assets/tree/main/htest/system/textures

I'm not sure if a file from the test version of Halloween should be added to the final version of this game.

Do you have other versions of this file?

**Comment by brizzly** [comment]
as far as I remember it may be the player skin but since we play in first player view we never see this cubic player.
It looks like a minecraft player model :) You can see it if you move to free camera view by typing a command in the console : 
pview 0

**Comment by brizzly** [comment]
found it :)
![body_Red](https://github.com/user-attachments/assets/3b8dd2fc-6b19-4ce5-b6aa-539f35085850)

**Comment by gbudny** [comment]
Hi

Thank you for the answer.

That's great news!

I don't see these two errors anymore:

https://gist.github.com/gbudny/3cf1f8f055a8cf60161b07e44e7a4314

Can you add it to a main branch?

I noticed that your website is offline.

What's happened with your website?

EDIT: I see that you use a different one.

**Comment by gbudny** [comment]
Thank you!
