### ISSUE TITLE
fatal error: KSound.h: No such file or directory

### ISSUE THREAD

**Issue by gbudny** [brizzly/Halloween3D#3]
Hi

Does mean it that I won't have sound in the game if I comment KSound.h?

Do you remember what libraries were used by the Linux version for sound?

I will comment it for now, but It 's a terrible solution.

**Comment by brizzly** [comment]
Playing sounds and music is always the tricky part as its very dependant on the platform target.
But it should not be hard nowadays to update this code with a good lib on Ubuntu system in order play Mp3 and/or OGGs.. I hope. feel free to fork and let me know how you achieve doing it? Can't stand to see the result on Ubuntu!

**Comment by gbudny** [comment]
I can close it now.
