### ISSUE TITLE
Halloween builds on Linux x86_64!

### ISSUE THREAD

**Issue by gbudny** [brizzly/Halloween3D#5]
Hi

I'm not programmer, so I can't improve your source code. I posted news at the pandora forum and Farox modify it so Halloween builds on Linux x86-64. The game still doesn't start, but I think it is nice progresss. Maybe you want 
review it and merge these changes:

https://pyra-handheld.com/boards/threads/the-commercial-game-halloween-fps-for-linux-is-now-the-open-source-project.99588/

**Comment by brizzly** [comment]
This is fantastic and also very interesting !!!!
Thank you for your effort, on my old project. 
I'm 100% ok for merging your changes. let me know how to do it please?
I guess the error is about loading PNG asset image but it should be tested more carefuly.

**Comment by gbudny** [comment]
That are changes made by Farox, but not me.

**Comment by brizzly** [comment]
Im ok for merging Farox changes, let me know how to do that please?

**Comment by farox1** [comment]
Hi
I'm Farox from OpenPandora Forum.
I have done some quick hack and changes to your code (thanks for relasing the code for this game) to be able to build on Linux (i build it on Linux Mint 19.3 x64).
I'm not a programmer but i like to thinker with code, and sometimes i enjoy build things.
The best way to send you the changes are that @gbudny add the modified files to his github space and then send you a Pull request here...but please i'm also not so expert on github.

**Comment by gbudny** [comment]
Hi

I want to inform you that the version created by Farox is on Github:

https://github.com/gbudny/Halloween3D-test

I removed the Linux binary files from distrib directory, and I added the modified version of the build file for Ubuntu 20.4. I have to prepare some Pull requests.

**Comment by brizzly** [comment]
Great ! Please send me a pull request 
You guys are awesome
Thank you for your effort 👍🏼

**Comment by gbudny** [comment]
> This is fantastic and also very interesting !!!! Thank you for your effort, on my old project. I'm 100% ok for merging your changes. let me know how to do it please? I guess the error is about loading PNG asset image but it should be tested more carefuly.

PNG? 

I had to install libjpeg-dev to build it , but Halloween can't start when It tries to load the tga image.

Do you think that the Linux version requires a package like libsoil-dev?

I intalled it, but it didn't fix this issue.

"SOIL is a tiny C library used primarily for uploading textures into OpenGL.
It supports loading BMP, PNG, JPG, TGA, DDS, PSD and HDR files as well as
saving into TGA, BMP and DDS Files.

It is also able to perform common functions needed in loading OpenGL textures.

This package contains everything needed to develop software using libsoil."

**Comment by brizzly** [comment]
Interesting
It seems a great lib
Maybe texture copy fails
I will have a look at it in 3 months as soon as I get a new computer

**Comment by gbudny** [comment]
> Interesting It seems a great lib Maybe texture copy fails I will have a look at it in 3 months as soon as I get a new computer

Great! 

I think that could be a popular open source game among Linux users. It is hard to give an example of other single-player horror games that don't require an original CD.

**Comment by gbudny** [comment]
These issues are solved now:

https://github.com/brizzly/Halloween3D/pull/9
https://github.com/brizzly/Halloween3D/pull/6
