### ISSUE TITLE
Two missing TGA images

### ISSUE THREAD

**Issue by gbudny** [brizzly/Halloween3D#8]
Hi

Farox found a solution to why TGA images weren't loading, but I noticed that the Linux version requires two TGA images:

https://gist.github.com/gbudny/3b3f3ad5cc1aba20ada76bfa21b27166#file-tga1

system/textures/systex/rayure.tga  - this file isn't available in the Windows version
system/textures/systex/citrouille.tga - I noticed that citrouille.jpg exists in this directory

Do you plan to add them?

Do you remember why the Linux version of Halloween requires them?

**Comment by brizzly** [comment]
I have just added them both into distrib / textures / systex and pushed it.
